######################## Paper Information ########################################
# Personal info
paper_name: "Trainability of IQP Quantum Circuit Born Machines Under Gaussian Initialization"

organization: Arizona State University 
sub_organization: School of Computing and Augmented Intelligence 
preprint : True # Set true if pre-print. False otherwise

######################## Paper Resources ########################################

paper_pdf: https://arxiv.org/pdf/2606.10179 # Main PDF Link here
# supplementary_pdf: Supplementary PDF here
# code: https://github.com/MPSLab-ASU/Project_Page_Template # GitHub link here
arXiv : https://arxiv.org/abs/2606.10179 # ArXiV Publication Link Here
# IEEE: https://ieeexplore.ieee.org/document/9187262 # IEEE Publication Link Here
#ACM: ACM Publication Link Here
# Additional icon links

favicon: assets/images/MPS_Lab.ico

main_media:
  source: assets/images/mpo_comm.png
  caption: |
    <b>Gate commutativity and cancellation in the computation of Γ(a)</b>. The figure highlights three types of gates based on their interaction with the observable: (1) Gates with no generator interaction with the observable (e.g., g5) commute and cancel out with their adjoints. (2) Gates with an even number of generator interactions with the observable (e.g., g4) acquire no net phase, allowing them to commute and cancel. (3) Gates with an odd number of generator interactions with the observable (e.g., g2) acquire a negative phase and do not cancel out, forming the effective reverse light cone Γ(a).



######################## DO NOT EDIT BELOW THIS LINE ########################################

# Footer
footer_show_references: true

#sass
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript


markdown: kramdown
permalink: pretty

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  "README.md",
  ]